version: '3'
services:

  postgres:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg!fcp
    ports:
      - "5432:5432"

  pgadmin:
    image: thajeztah/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: pg!fcp
      PGADMIN_ENABLE_TLS: "False"
    ports:
      - "5050:5050"
    depends_on:
      - postgres
